# Generated by Django 4.1.5 on 2023-02-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_acct_no_alter_member_acct_pw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cust_name',
        ),
    ]
