# Generated by Django 4.1.5 on 2023-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_member_cust_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cust_name',
            field=models.CharField(max_length=8, null=True, verbose_name='성명'),
        ),
    ]
