# Generated by Django 4.1.5 on 2023-02-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_stock_stock_ind_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='buy_price',
            field=models.CharField(max_length=16, verbose_name='매수가'),
        ),
    ]
