# Generated by Django 4.1.5 on 2023-02-21 15:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_alter_dividend_options_alter_dividend_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Protfolio',
            new_name='Portfolio',
        ),
    ]
