# Generated by Django 4.1.5 on 2023-02-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(verbose_name='주식 비율')),
                ('bond', models.IntegerField(verbose_name='채권 비율')),
                ('real_asset', models.IntegerField(verbose_name='실물자산 비율')),
                ('crypto', models.IntegerField(verbose_name='가상화폐 비율')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '총자산 포트폴리오',
                'verbose_name_plural': '총자산 포트폴리오',
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.IntegerField(verbose_name='1월')),
                ('february', models.IntegerField(verbose_name='2월')),
                ('march', models.IntegerField(verbose_name='3월')),
                ('april', models.IntegerField(verbose_name='4월')),
                ('may', models.IntegerField(verbose_name='5월')),
                ('june', models.IntegerField(verbose_name='6월')),
                ('july', models.IntegerField(verbose_name='7월')),
                ('august', models.IntegerField(verbose_name='8월')),
                ('september', models.IntegerField(verbose_name='9월')),
                ('october', models.IntegerField(verbose_name='10월')),
                ('november', models.IntegerField(verbose_name='11월')),
                ('december', models.IntegerField(verbose_name='12월')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
    ]
