# Generated by Django 4.1.5 on 2023-02-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividend',
            options={'verbose_name': '배당금 포트폴리오', 'verbose_name_plural': '배당금 포트폴리오'},
        ),
        migrations.AlterModelTable(
            name='dividend',
            table='dividend',
        ),
    ]
