# Generated by Django 4.1.7 on 2023-02-18 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=16, verbose_name='STOCK_NAME')),
                ('stock_code', models.CharField(max_length=16, verbose_name='STOCK_CODE')),
                ('stock_open_price', models.IntegerField(verbose_name='STOCK_OPEN_PRICE')),
                ('stock_high_price', models.IntegerField(verbose_name='STOCK_HIGH_PRICE')),
                ('stock_low_price', models.IntegerField(verbose_name='STOCK_LOW_PRICE')),
                ('stock_close_price', models.IntegerField(verbose_name='STOCK_CLOSE_PRICE')),
                ('stock_volume', models.IntegerField(verbose_name='STOCK_VOLUME')),
                ('stock_amount', models.IntegerField(verbose_name='STOCK_AMOUNT')),
                ('stock_change_rate', models.IntegerField(verbose_name='STOCK_CHANGE_RATE')),
            ],
            options={
                'verbose_name': '주식정보',
                'verbose_name_plural': '주식정보',
                'db_table': 'shinhan_stock',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.IntegerField(verbose_name='카트')),
                ('tstamp', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='주식')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알파 카트',
                'verbose_name_plural': '알파 카트',
                'db_table': 'shinhan_stock_cart',
            },
        ),
    ]
