# Generated by Django 4.1.5 on 2023-02-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '장바구니', 'verbose_name_plural': '장바구니'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '주식', 'verbose_name_plural': '주식'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tstamp',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_change_rate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_close_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_high_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_low_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_open_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_volume',
        ),
        migrations.AddField(
            model_name='cart',
            name='buy_price',
            field=models.IntegerField(default=0, verbose_name='매수가'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='buy_quantity',
            field=models.IntegerField(default=0, verbose_name='매수수량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_cp',
            field=models.IntegerField(default=0, verbose_name='현재가'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_pg',
            field=models.IntegerField(default=0, verbose_name='전일대비금액'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_pr',
            field=models.IntegerField(default=0, verbose_name='전일대비등락률'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_code',
            field=models.CharField(max_length=16, verbose_name='종목코드'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=16, verbose_name='종목명'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='stock_cart',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.IntegerField(verbose_name='예수금')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.cart', verbose_name='장바구니')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '주식잔고',
                'verbose_name_plural': '주식잔고',
                'db_table': 'balance',
            },
        ),
    ]
