# Generated by Django 4.1.5 on 2023-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_stock_ind_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_cp',
            field=models.CharField(max_length=32, verbose_name='현재가'),
        ),
    ]
