# Generated by Django 4.1.5 on 2023-02-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stock_stock_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_pg',
            field=models.CharField(max_length=16, verbose_name='전일대비금액'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_pr',
            field=models.CharField(max_length=16, verbose_name='전일대비등락률'),
        ),
    ]
