# Generated by Django 4.1.5 on 2023-02-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stock_stock_pg_alter_stock_stock_pr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_ind_code',
        ),
    ]
