# Generated by Django 4.1.5 on 2023-02-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_cart_buy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='stock',
        ),
        migrations.AddField(
            model_name='cart',
            name='stock_code',
            field=models.CharField(default=0, max_length=16, verbose_name='종목코드'),
            preserve_default=False,
        ),
    ]
