# Generated by Django 4.1.5 on 2023-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='age',
            new_name='acct_pw',
        ),
        migrations.AddField(
            model_name='member',
            name='acct_no',
            field=models.IntegerField(default=0, unique=True, verbose_name='계좌번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='cust_name',
            field=models.CharField(default='비회원', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
