# Generated by Django 4.1.5 on 2023-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rename_age_member_acct_pw_member_acct_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='acct_pw',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
