# Generated by Django 4.1.5 on 2023-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_acct_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='acct_no',
            field=models.IntegerField(null=True, unique=True, verbose_name='계좌번호'),
        ),
        migrations.AlterField(
            model_name='member',
            name='acct_pw',
            field=models.CharField(default='0000', max_length=4, null=True, verbose_name='계좌 비밀번호'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cust_name',
            field=models.CharField(max_length=8, null=True, verbose_name='사용자'),
        ),
    ]
